# Generated by Django 5.1.1 on 2024-10-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_review_reviews_rename_user_reviews_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='user_id',
            new_name='user',
        ),
    ]
