# Generated by Django 5.1.1 on 2024-10-12 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_movie_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='movie_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.reviews'),
        ),
    ]
