# Generated by Django 5.1.1 on 2024-10-13 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_reviews_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-created_date']},
        ),
    ]
